providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake"]
nixLibs = ["gcc-unwrapped"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx drizzle-kit push", "npm run build"]

[start]
cmd = "npm run start"
